version: '2'
networks:
  nw:
    driver: bridge

volumes:
  jenkins-data:

services:
  jenkins: .
    ports:
      - "80:8080"
    volumes:
      - jenkins-data:/var/jenkins_home/casc
    networks:
      - nw