jobs:
  - script: >
      pipelineJob("Seed-jobs") {
      definition {
          cpsScm {
              scm {
                  git{
                    remote {
                      url("https://github.com/automationtimes/nodeapp/")
                    }
                    branch("*/master")
                  }
              }
          triggers {
            githubPush()
          }

          }
        }
      }